version: '3.8'

services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: auth__db
      POSTGRES_USER: auth__user
      POSTGRES_PASSWORD: auth__password
    ports:
      - 25032:5432
