version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    hostname: rabbitmq
    ports:
      - 2572:5672
      - 25672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
  server:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/api_conf.d:/etc/nginx/api_conf.d
      - ./nginx/api_backends.conf:/etc/nginx/api_backends.conf
      - ./nginx/api_gateway.conf:/etc/nginx/api_gateway.conf
    network_mode: host
volumes:
  blog-data:
  rabbitmq_data:
  rabbitmq_log:
